# Generated by Django 4.0.4 on 2022-04-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
