# Generated by Django 4.0.4 on 2022-04-27 05:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0002_estudiante_apellido_estudiante_dig_verificador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('siglas', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jefe_Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=40, null=True)),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=b'I01\n')),
                ('password', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'Pendiente')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subdirector_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=40, null=True)),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=b'I01\n')),
                ('password', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vicedecano_Docencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=40, null=True)),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=b'I01\n')),
                ('password', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('year_crecion', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('id_carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('id_vicedecano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.vicedecano_docencia')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_subdirector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.subdirector_docente')),
                ('id_vicedecano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.vicedecano_docencia')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.departamento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_jefeCarrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.jefe_carrera'),
        ),
    ]
