# Generated by Django 4.0.4 on 2022-04-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0003_carrera_estado_evaluacion_jefe_carrera_mensaje_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_Evaluacion',
        ),
        migrations.DeleteModel(
            name='Tipo_Observacion',
        ),
    ]
