# Generated by Django 4.0.4 on 2022-04-29 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gccu', '0006_delete_estado_evaluacion_delete_tipo_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('componente', models.CharField(choices=[('L', 'Laboratorio'), ('T', 'Teoría')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas_PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Cambio_Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAnterior', models.DateField()),
                ('fechaNueva', models.DateField()),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cambio_Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacionAnterior', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ponderacionNueva', models.DecimalField(decimal_places=3, max_digits=4)),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinacion_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinacion_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioEstudiante', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinacion_Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinacion', models.CharField(max_length=1)),
                ('seccion', models.PositiveSmallIntegerField()),
                ('bloques_horario', models.CharField(max_length=16)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(decimal_places=3, max_digits=4)),
                ('mejor_nota', models.DecimalField(decimal_places=3, max_digits=4)),
                ('peor_nota', models.DecimalField(decimal_places=3, max_digits=4)),
                ('desviacionEstandar', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.coordinacion_seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaEvActual', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('ponderacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Evaluada')], max_length=1)),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True)),
                ('archivoAdjunto', models.FileField(null=True, upload_to='')),
                ('tipo', models.CharField(choices=[('P', 'Privada'), ('G', 'General')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semestre', models.IntegerField(choices=[(1, 1), (2, 2)])),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('archivoAdjunto', models.FileField(null=True, upload_to='')),
                ('respuesta', models.TextField(blank=True, default='')),
                ('fecha_respuesta', models.DateTimeField(default=0, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'Pendiente')], default='', max_length=1)),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.docente')),
            ],
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='dig_verificador',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='password',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='jefe_carrera',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='jefe_carrera',
            name='dig_verificador',
        ),
        migrations.RemoveField(
            model_name='jefe_carrera',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jefe_carrera',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='jefe_carrera',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jefe_carrera',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='subdirector_docente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='subdirector_docente',
            name='dig_verificador',
        ),
        migrations.RemoveField(
            model_name='subdirector_docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subdirector_docente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='subdirector_docente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subdirector_docente',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='vicedecano_docencia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='vicedecano_docencia',
            name='dig_verificador',
        ),
        migrations.RemoveField(
            model_name='vicedecano_docencia',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vicedecano_docencia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vicedecano_docencia',
            name='password',
        ),
        migrations.RemoveField(
            model_name='vicedecano_docencia',
            name='rut',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jefe_carrera',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subdirector_docente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vicedecano_docencia',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.departamento'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id_jefeCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.jefe_carrera'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_subdirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.subdirector_docente'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_vicedecano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.vicedecano_docencia'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='id_vicedecano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.vicedecano_docencia'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='siglas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='plan_estudio',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='plan_estudio',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.carrera'),
        ),
        migrations.AddField(
            model_name='solicitud_revision',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.estudiante'),
        ),
        migrations.AddField(
            model_name='solicitud_revision',
            name='id_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.evaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_observacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.observacion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_tipoEvaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.tipo_evaluacion'),
        ),
        migrations.AddField(
            model_name='coordinacion_seccion',
            name='id_semetre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.semestre'),
        ),
        migrations.AddField(
            model_name='coordinacion_estudiante',
            name='id_coordinacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.coordinacion_seccion'),
        ),
        migrations.AddField(
            model_name='coordinacion_estudiante',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.estudiante'),
        ),
        migrations.AddField(
            model_name='coordinacion_docente',
            name='id_coordinacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.coordinacion_seccion'),
        ),
        migrations.AddField(
            model_name='coordinacion_docente',
            name='id_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.docente'),
        ),
        migrations.AddField(
            model_name='cambio_ponderacion',
            name='id_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.evaluacion'),
        ),
        migrations.AddField(
            model_name='cambio_fecha',
            name='id_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.evaluacion'),
        ),
        migrations.AddField(
            model_name='asignaturas_planestudio',
            name='id_planEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.plan_estudio'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.coordinador'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_tipoAsignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccu.tipo_asignatura'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_semestreIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.semestre'),
        ),
    ]
