# Generated by Django 4.0.4 on 2022-04-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0008_calificacion_cambio_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_planEstudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.plan_estudio'),
        ),
    ]
