# Generated by Django 4.0.4 on 2022-05-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0009_estudiante_id_planestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jefe_carrera',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jefe_carrera',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subdirector_docente',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subdirector_docente',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vicedecano_docencia',
            name='dig_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vicedecano_docencia',
            name='rut',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
