# Generated by Django 4.0.4 on 2022-05-02 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0011_asignatura_isautogestionada_asignatura_ismbi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='id_coordinacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.coordinacion_seccion'),
        ),
    ]
