# Generated by Django 4.0.4 on 2022-05-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0016_alter_plan_estudio_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_revision',
            name='id_coordinacionSeccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.coordinacion_seccion'),
        ),
    ]
