# Generated by Django 4.0.4 on 2022-05-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0018_alter_solicitud_revision_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_revision',
            name='archivoAdjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitud_revision',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
