# Generated by Django 4.0.4 on 2022-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0020_remove_solicitud_revision_id_coordinacionseccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacion_estudiante',
            name='promedioEstudiante',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
