# Generated by Django 4.0.4 on 2022-05-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0021_alter_coordinacion_estudiante_promedioestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='id_observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.observacion'),
        ),
    ]
