# Generated by Django 4.0.4 on 2022-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0023_alter_calificacion_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fechaEntrega',
            field=models.DateField(blank=True),
        ),
    ]
