# Generated by Django 4.0.4 on 2022-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0024_alter_evaluacion_fechaentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fechaEntrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
