# Generated by Django 4.0.4 on 2022-05-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0026_alter_calificacion_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambio_nota',
            name='fecha_cambio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='solicitud_revision',
            name='actual_nota',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_revision',
            name='anterior_nota',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_revision',
            name='id_calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.calificacion'),
        ),
    ]
