# Generated by Django 4.0.4 on 2022-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0027_cambio_nota_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_revision',
            name='anterior_nota',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
