# Generated by Django 4.0.4 on 2022-05-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0028_alter_solicitud_revision_anterior_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id_observacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='id_observacion',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='obs_privada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='obs_general',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
    ]
