# Generated by Django 4.0.4 on 2022-05-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0030_alter_cambio_nota_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='ponderacion',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
