# Generated by Django 4.0.4 on 2022-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0032_cambio_fecha_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_revision',
            name='estado',
            field=models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'Pendiente'), ('E', 'En revisión')], default='', max_length=1),
        ),
    ]
