# Generated by Django 4.0.4 on 2022-06-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0033_alter_solicitud_revision_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='observaciones/estudiantes/'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='observaciones/evaluacion/'),
        ),
    ]
