# Generated by Django 4.0.4 on 2022-06-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0034_calificacion_adjunto_alter_evaluacion_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
