# Generated by Django 4.0.4 on 2022-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0036_alter_asignatura_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio_nota',
            name='actual_nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='cambio_nota',
            name='anterior_nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
