# Generated by Django 4.0.4 on 2022-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0037_alter_cambio_nota_actual_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_revision',
            name='actual_nota',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_revision',
            name='anterior_nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
