# Generated by Django 4.0.4 on 2022-07-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gccu', '0038_alter_solicitud_revision_actual_nota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_estudio',
            old_name='year_crecion',
            new_name='year_creacion',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='id_vicedecano',
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gccu.facultad'),
        ),
        migrations.AlterField(
            model_name='coordinacion_estudiante',
            name='promedioEstudiante',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
